// What the OTA runtime version hashes (docs/OTA.md). Left out: package.json scripts (tool scripts like replay:* never
// reach the native build) and .gitignore (ios/ and android/ are generated by prebuild, never committed). Anything else
// native, from app.json to patches/, still makes a new runtime that needs a new IPA/APK.
/** @type {import('expo/fingerprint').Config} */
const config = {
  sourceSkips: ["PackageJsonScriptsAll", "GitIgnore"],
};

module.exports = config;
