// Is a position inside Ukraine (SPEC §3.3)? Spoofed fixes often land abroad. The polygon is
// Ukraine's OSM boundary buffered by 2 km (ukraine-border.ts, generated by tools/tiles).

import { UKRAINE_BORDER } from "./ukraine-border";

interface Ring {
  xy: readonly number[];
  minLon: number;
  maxLon: number;
  minLat: number;
  maxLat: number;
}

function ring(xy: readonly number[]): Ring {
  const r: Ring = { xy, minLon: Infinity, maxLon: -Infinity, minLat: Infinity, maxLat: -Infinity };
  for (let i = 0; i < xy.length; i += 2) {
    r.minLon = Math.min(r.minLon, xy[i]);
    r.maxLon = Math.max(r.maxLon, xy[i]);
    r.minLat = Math.min(r.minLat, xy[i + 1]);
    r.maxLat = Math.max(r.maxLat, xy[i + 1]);
  }
  return r;
}

const RINGS = UKRAINE_BORDER.map(ring);

/** Even-odd ray casting over one ring (flat [lon, lat, …]). */
function inRing(r: Ring, lat: number, lon: number): boolean {
  if (lon < r.minLon || lon > r.maxLon || lat < r.minLat || lat > r.maxLat) return false;
  const xy = r.xy;
  let inside = false;
  for (let i = 0, j = xy.length - 2; i < xy.length; j = i, i += 2) {
    const xi = xy[i];
    const yi = xy[i + 1];
    const xj = xy[j];
    const yj = xy[j + 1];
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

export function insideUkraine(p: { lat: number; lon: number }): boolean {
  return RINGS.some((r) => inRing(r, p.lat, p.lon));
}
