"""The world the app draws around the active map region (`style/world.geojson`, SPEC §3.8).

A map pack holds tiles for its region only, and at low zoom those tiles carry whatever slice of the
world they happen to cover, so the map looked different at every zoom. The app covers everything
outside the active region with this instead: water, land, country borders and country names from
Natural Earth (Ukrainian point of view), and Ukraine as its oblasts along their OSM boundaries.
Each oblast feature flags the regions whose tiles already show it (`covered:ukraine`, `covered:kyiv`),
so any region, all of Ukraine or one oblast, leaves a hole for its own map.

Russia is not land here: it is the Ukrainian Sea (an easter egg).

Generated by `python -m tiles.cli world` and committed, like `regions/*.poly`: builds need no
network lookups. Shipped with the shared map files.
"""

from __future__ import annotations

import json
import sqlite3
import time
import urllib.request
import zipfile
from pathlib import Path
from typing import Any, Callable

import shapely
from shapely import wkb
from shapely.geometry import LineString, MultiLineString, Point, Polygon, box, mapping, shape
from shapely.geometry.base import BaseGeometry
from shapely.ops import linemerge, polygonize, unary_union
from shapely.strtree import STRtree

from .region import USER_AGENT, read_poly

NE_MEMBER = "packages/natural_earth_vector.sqlite"
NE_COUNTRIES = "ne_10m_admin_0_countries_ukr"
NE_BORDERS = "ne_10m_admin_0_boundary_lines_land"
NOMINATIM_FINE = (  # ~1 m: Nominatim refuses some oblasts unsimplified
    "https://nominatim.openstreetmap.org/lookup?osm_ids=R{id}&format=json&polygon_geojson=1&polygon_threshold=0.00001"
)
SEA = "RUS"
SEA_NAME = {"name": "Ukrainian Sea", "name_uk": "Українське море"}
# Where it is named besides Russia's label point: off Ukraine's border, for the zooms that show it.
SEA_NAMED_NEAR = [(36.6, 52.3), (40.3, 49.8), (42.3, 47.0)]
HOME = "UKR"
WHOLE = "ukraine"  # the region whose map covers every oblast

NEAR = box(12.0, 40.0, 46.0, 58.0)  # Ukraine and its neighbours, drawn in more detail
FAR_TOLERANCE_DEG = 0.05  # ~4 km: the rest of the world is only seen zoomed out
NEAR_TOLERANCE_DEG = 0.003  # ~250 m: neighbouring countries
OBLAST_TOLERANCE_DEG = 0.0005  # an oblast edge is where a region's real map meets the drawn one
SEAM_DEG = 0.03  # Natural Earth's borders are a few hundred metres off OSM's: neighbours grow to meet Ukraine
MIN_PART_DEG2 = 0.005  # drops specks of islands
MERCATOR_LAT = 85.0511
DIGITS = 4  # ~10 m


def natural_earth(ne_zip: Path, tmp_dir: Path) -> sqlite3.Connection:
    sqlite_path = tmp_dir / NE_MEMBER
    if not sqlite_path.exists():
        with zipfile.ZipFile(ne_zip) as z:
            z.extract(NE_MEMBER, tmp_dir)
    return sqlite3.connect(sqlite_path)


def fetch_boundary(relation_id: int, cache_dir: Path) -> BaseGeometry:
    """Boundary at ~1 m, cached: Nominatim allows one request per second."""
    path = cache_dir / f"R{relation_id}.geojson"
    if not path.exists():
        req = urllib.request.Request(NOMINATIM_FINE.format(id=relation_id), headers={"User-Agent": USER_AGENT})
        for wait in (5, 15, 45, 0):  # a throttled lookup comes back empty
            with urllib.request.urlopen(req, timeout=300) as res:
                data = json.load(res)
            if data or not wait:
                break
            time.sleep(wait)
        if not data:
            raise ValueError(f"relation {relation_id} not found")
        cache_dir.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(data[0]["geojson"]), encoding="utf-8")
        time.sleep(1.1)
    return shape(json.loads(path.read_text(encoding="utf-8")))


def polygons(geom: BaseGeometry) -> list[Polygon]:
    if isinstance(geom, Polygon):
        return [] if geom.is_empty else [geom]
    return [g for part in getattr(geom, "geoms", []) for g in polygons(part)]


def lines(geom: BaseGeometry) -> list[LineString]:
    if isinstance(geom, LineString):
        return [] if geom.is_empty else [geom]
    if isinstance(geom, MultiLineString):
        merged = linemerge(geom)
        return [merged] if isinstance(merged, LineString) else [g for g in merged.geoms if not g.is_empty]
    return [g for part in getattr(geom, "geoms", []) for g in lines(part)]


def mosaic(areas: list[BaseGeometry]) -> list[BaseGeometry]:
    """Areas simplified one by one (gaps and overlaps of a metre between neighbours) as a clean
    coverage: every face of their noded outlines goes to the area holding it, a sliver to the nearest."""
    areas = [shapely.make_valid(a) for a in areas]
    tree = STRtree(areas)
    owned: list[list[Polygon]] = [[] for _ in areas]
    for face in polygonize(unary_union([a.boundary for a in areas])):
        point = face.representative_point()
        inside = tree.query(point, predicate="within")
        if len(inside):
            owned[int(inside[0])].append(face)
        elif face.area < 1e-5:  # a gap between neighbours, not a hole in the country
            owned[int(tree.nearest(point))].append(face)
    return [unary_union(parts) for parts in owned]


def two_detail(geom: BaseGeometry) -> BaseGeometry:
    """Near Ukraine in more detail than the rest of the world."""
    far = geom.difference(NEAR).simplify(FAR_TOLERANCE_DEG)
    return unary_union([far, geom.intersection(NEAR).simplify(NEAR_TOLERANCE_DEG)])


def covered(regions: list[str]) -> dict[str, int]:
    return {f"covered:{r}": 1 for r in regions}


def build(ne: sqlite3.Connection, registry: dict[str, Any], regions_dir: Path, boundary: Callable[[int], BaseGeometry]) -> list[dict]:
    """GeoJSON features: `kind` water / land / border / region-border / label."""
    countries = {
        a3: (wkb.loads(g), name, int(rank), x, y)
        for a3, g, name, rank, x, y in ne.execute(f"SELECT adm0_a3, GEOMETRY, name_en, labelrank, label_x, label_y FROM {NE_COUNTRIES}")
    }
    land_all = unary_union([g for g, *_ in countries.values()])
    russia = countries[SEA][0]
    neighbours = unary_union([g for a3, (g, *_) in countries.items() if a3 not in (SEA, HOME)])

    # Ukraine as its oblasts (territorial sea included), simplified together so neighbours keep one shared edge.
    names = [n for n in registry if n != WHOLE]
    oblasts = [shapely.make_valid(g) for g in shapely.coverage_simplify(mosaic([boundary(registry[n]["relation"]) for n in names]), OBLAST_TOLERANCE_DEG)]
    ukraine = unary_union(oblasts)
    outlines = {r: read_poly(regions_dir / f"{r}.poly") for r in registry if r != WHOLE}
    covers = [
        [WHOLE] + [r for r, outline in outlines.items() if r == names[i] or outline.contains(g.representative_point())]
        for i, g in enumerate(oblasts)
    ]

    features: list[dict] = []

    def add(kind: str, geom: BaseGeometry, **props: Any) -> None:
        # Outer rings counter-clockwise, holes clockwise (RFC 7946): MapLibre tells holes by their winding.
        geom = shapely.orient_polygons(shapely.set_precision(geom, 10**-DIGITS))
        if not geom.is_empty:
            features.append({"type": "Feature", "properties": {"kind": kind, **props}, "geometry": mapping(geom)})

    world = box(-180, -MERCATOR_LAT, 180, MERCATOR_LAT)
    add("water", world.difference(unary_union([Polygon(p.exterior) for p in polygons(ukraine)])))

    seam = ukraine.buffer(SEAM_DEG).intersection(neighbours.buffer(SEAM_DEG)).intersection(land_all).difference(russia)
    foreign = two_detail(unary_union([neighbours, seam])).intersection(world).difference(ukraine)
    add("land", unary_union([p for p in polygons(foreign) if p.area >= MIN_PART_DEG2]))

    coast = land_all.intersection(NEAR).simplify(NEAR_TOLERANCE_DEG)  # oblasts not on the map need no finer coast
    for g, regions in zip(oblasts, covers):
        add("land", g.intersection(coast), **covered(regions))
        add("water", g.difference(coast), **covered(regions))

    # Country borders, Russia's left out (it is sea) and Ukraine's taken from its oblasts.
    rows = ne.execute(f"SELECT GEOMETRY, adm0_a3_l, adm0_a3_r, fclass_ua FROM {NE_BORDERS}")
    foreign_borders = unary_union([wkb.loads(g) for g, l, r, fclass in rows if not {l, r} & {SEA, HOME} and fclass != "Unrecognized"])
    add("border", two_detail(foreign_borders.difference(ukraine)))
    add("border", ukraine.boundary.intersection(neighbours.difference(russia.buffer(SEAM_DEG)).buffer(SEAM_DEG)))

    # Oblast borders on land, hidden where one map covers both sides (its own tiles draw them).
    for i in range(len(oblasts)):
        for j in range(i + 1, len(oblasts)):
            shared = [l for l in lines(oblasts[i].boundary.intersection(oblasts[j].boundary)) if l.length > 1e-4]
            if shared:
                both = [r for r in covers[i] if r in covers[j]]
                add("region-border", unary_union(shared).intersection(coast), **covered(both))

    for a3, (_, name, rank, x, y) in sorted(countries.items()):
        if a3 != SEA and name:
            add("label", Point(x, y), name=name, rank=rank)
    _, _, _, x, y = countries[SEA]
    add("sea-label", Point(x, y), **SEA_NAME, near=0)
    for x, y in SEA_NAMED_NEAR:
        add("sea-label", Point(x, y), **SEA_NAME, near=1)
    return features


def world_geojson(features: list[dict]) -> str:
    return json.dumps({"type": "FeatureCollection", "features": features}, separators=(",", ":"), ensure_ascii=False)
